### ISSUE TITLE
issue1

### ISSUE THREAD

**Issue by bwong1997** [bwong1997/CDGD304-01#4]
can't figure out how to use z-index with svg text (index3.html)????????????

**Comment by saulbaizman** [comment]
BoYi,

This is a very unusual question. The z-index property is used in conjunction with the other layout properties: position, float, clear, and display. Have you looked at the [learnlayout.com](http://learnlayout.com) site?

Can we take a closer look at this on Friday?

S

**Comment by bwong1997** [comment]
Okay......that’s kind of what I thought but I wasn’t sure. And yes I looked
at the website and it wasn’t too helpful and I’m basically still unclear on
what I need to do to fix my stuff. But yeah. I’ll talk to you on Friday
about it.
